apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
  labels:
    app: java-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
        - name: java-webapp
          image: guruprasathpgp/java-webapp:latest
          ports:
            - containerPort: 8080
